### ISSUE TITLE
通用顶级域名被拦截

### ISSUE THREAD

**Issue by star1145209** [fordes123/ad-filters-subscriber#24]
如下图.com域名被拦截（暂不清楚是规则问题还是合并处理过程bug），这个情况以往出现好几次，有次拦截规则是.co^，也导致所有.com被拦截。

![Screenshot_2024-05-25-06-33-36-639_com android browser-edit](https://github.com/fordes123/ad-filters-subscriber/assets/10861842/73c3e40b-8a68-46e2-9318-9ae1e0fdd878)

如果是规则偶尔出问题，能否增加判断条件例如：
1.每条规则长度小于5个字符自动删除
2.判断“.”前面字符数小于4个字符自动删除

**Comment by fordes123** [comment]
收到，正在排查这个问题

**Comment by star1145209** [comment]
> 收到，正在排查这个问题

谢谢大佬，我用的就是您readme里推荐的fork（https://github.com/xndeye/adblock_list）

**Comment by fordes123** [comment]
程序虽然会对规则进行处理，但是仅用于分类和去重，写入到文件的还是来自原始文件的规则  
目前还无法确定 错误规则来自上游 还是 由程序错误导致

**Comment by star1145209** [comment]
> 程序虽然会对规则进行处理，但是仅用于分类和去重，写入到文件的还是来自原始文件的规则 目前还无法确定 错误规则来自上游 还是 由程序错误导致

我尝试在Util.java文件里clearRule加上content.length() > 7，但是貌似无法达到预期效果

**Comment by fordes123** [comment]
经测试为写文件覆写导致的问题，已于 #26 修复
