### ISSUE TITLE
大佬，是否能帮我看一下问题出现在哪里吗，我复制了你的项目增加了许多过滤器，然后运行失败了

### ISSUE THREAD

**Issue by xiulou23** [fordes123/ad-filters-subscriber#28]
项目地址：https://github.com/xiulou23/AdguardHome-demonicAsura?tab=readme-ov-file
![image](https://github.com/user-attachments/assets/a4e76a41-ac26-4382-95bc-999ffdd64f44)
没有增加过滤器时是能运行成功的，增加过滤器后就运行失败了
![image](https://github.com/user-attachments/assets/31184b8c-015d-4647-8dd4-a39b58f858c3)

**Comment by fordes123** [comment]
> 项目地址：https://github.com/xiulou23/AdguardHome-demonicAsura?tab=readme-ov-file ![image](https://private-user-images.githubusercontent.com/133690386/358476192-a4e76a41-ac26-4382-95bc-999ffdd64f44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTI3NDAsIm5iZiI6MTcyMzc5MjQ0MCwicGF0aCI6Ii8xMzM2OTAzODYvMzU4NDc2MTkyLWE0ZTc2YTQxLWFjMjYtNDM4Mi05NWJjLTk5OWZmZGQ2NGY0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNzE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTJhZmI0NTk1YzllMzlkOTk0YzkzMWNlZTk5MmI3ZTBjMjAyZDI2NWNkYjAwZDhkOTZhM2M4ZmEzZmQzM2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Grr79UrIN5wf2gGXDPeBwgkwNhB3hgY5zOw0BDuyMAY) 没有增加过滤器时是能运行成功的，增加过滤器后就运行失败了 ![image](https://private-user-images.githubusercontent.com/133690386/358476414-31184b8c-015d-4647-8dd4-a39b58f858c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTI3NDAsIm5iZiI6MTcyMzc5MjQ0MCwicGF0aCI6Ii8xMzM2OTAzODYvMzU4NDc2NDE0LTMxMTg0YjhjLTAxNWQtNDY0Ny04ZGQ0LWEzOWI1OGY4NThjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNzE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmMxMmU5MGNiMDdjM2NlMTlkNDY0N2E0Yzc2OGVhNmUyNzA3Y2UxOTdjZDRjMDYyM2UwOTdhOWFhZTlmMGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QZpv9yPE2_p4L32h9Z1dso5WwXmAEzpY5iDT_eEbRKQ)

把类似的地方外层的单引号改成双引号 
![image](https://github.com/user-attachments/assets/96b7c412-4391-4029-b965-b85ec4181066)

像下面这样：
```yaml
      - name: "HaGeZi's Fake DNS Blocklist"
        path: 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/fake.txt'
```

**Comment by xiulou23** [comment]
> > 项目地址：https://github.com/xiulou23/AdguardHome-demonicAsura?tab=readme-ov-file ![image](https://private-user-images.githubusercontent.com/133690386/358476192-a4e76a41-ac26-4382-95bc-999ffdd64f44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTI3NDAsIm5iZiI6MTcyMzc5MjQ0MCwicGF0aCI6Ii8xMzM2OTAzODYvMzU4NDc2MTkyLWE0ZTc2YTQxLWFjMjYtNDM4Mi05NWJjLTk5OWZmZGQ2NGY0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNzE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTJhZmI0NTk1YzllMzlkOTk0YzkzMWNlZTk5MmI3ZTBjMjAyZDI2NWNkYjAwZDhkOTZhM2M4ZmEzZmQzM2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Grr79UrIN5wf2gGXDPeBwgkwNhB3hgY5zOw0BDuyMAY) 没有增加过滤器时是能运行成功的，增加过滤器后就运行失败了 ![image](https://private-user-images.githubusercontent.com/133690386/358476414-31184b8c-015d-4647-8dd4-a39b58f858c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTI3NDAsIm5iZiI6MTcyMzc5MjQ0MCwicGF0aCI6Ii8xMzM2OTAzODYvMzU4NDc2NDE0LTMxMTg0YjhjLTAxNWQtNDY0Ny04ZGQ0LWEzOWI1OGY4NThjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNzE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmMxMmU5MGNiMDdjM2NlMTlkNDY0N2E0Yzc2OGVhNmUyNzA3Y2UxOTdjZDRjMDYyM2UwOTdhOWFhZTlmMGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QZpv9yPE2_p4L32h9Z1dso5WwXmAEzpY5iDT_eEbRKQ)
> 
> 把类似的地方外层的单引号改成双引号 ![image](https://private-user-images.githubusercontent.com/52121395/358501447-96b7c412-4391-4029-b965-b85ec4181066.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTQ5MjIsIm5iZiI6MTcyMzc5NDYyMiwicGF0aCI6Ii81MjEyMTM5NS8zNTg1MDE0NDctOTZiN2M0MTItNDM5MS00MDI5LWI5NjUtYjg1ZWM0MTgxMDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA3NTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDI2ZTQ1MDIwMjM0NTIwODMxYmI1NDdiODczMjQwY2RkMmZjZGYxYWExZTk5YTRiNDkyOTdlYWI5OGU0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q2MdtCx32x9baxSFirCOeHq92opsPXEVm7NYXejr2l0)
> 
> 像下面这样：
> 
> ```yaml
>       - name: "HaGeZi's Fake DNS Blocklist"
>         path: 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/fake.txt'
> ```

![image](https://github.com/user-attachments/assets/27f3a09c-8287-488c-9e5d-3aa4375725d7)
我改了，目前是提交方面出了问题

**Comment by fordes123** [comment]
```
remote: error: File rule/easylist.txt is 121.14 MB; this exceeds GitHub's file size limit of 100.00 MB       
```
生成的规则文件太大，github 最大支持 100mb，尝试减少上游规则吧

**Comment by fordes123** [comment]
追求大而全的规则集是舍本逐末
规则并非越多越好，它们中大部分的域名你可能一辈子都不会访问，还有很多域名是失效的
