### ISSUE TITLE
建议改进 dns.txt 的过滤规则

### ISSUE THREAD

**Issue by YishaBei** [fordes123/ad-filters-subscriber#29]
个人观察到有很多适用于 `AdGuard Home` 的规则并没有正确分配到 dns.txt，而是被分配到 modify.txt
例如：
```
||xmupdate.*.xiaomi.com^$important
||*.log.nexon.io^
@@||connectivity*.gstatic.com
```
其中，基本的通配符 AdGuard Home 是可以正确识别并匹配的，但生成的规则却没有分配到 dns.txt

另外 有些特殊规则，例如：
```
||httpdns*.dbankcloud.$important
||hiboard-*.dbankcdn.$important
```
该规则中最后并没有指定顶级域，而 AdGuard Home 则会自动模糊匹配，在上文中，华为注册了.cn .com .ru .eu .asia 等同名顶级域，因此这样模糊匹配是最佳的选择（参考）：

![image](https://github.com/user-attachments/assets/8a4ce194-e4d2-45c1-ac25-8be042663af7)
![image](https://github.com/user-attachments/assets/d422edad-00ab-4d83-9ce7-2b95a58c0142)

而重复规则也是会出现的：
```
||track.uc.cn
||track.uc.cn^
||data.bilibili.com^
||data.bilibili.com^
0.0.0.0	data.bilibili.com
||data.bilibili.com^
```
![image](https://github.com/user-attachments/assets/2ad4c293-5359-4347-930d-801f4272627a)

在我初次生成规则时[[文件参考]](https://raw.githubusercontent.com/YishaBei/adblock-filter/2c367c734743b82276dbfd94912a2269f5569af2/rule/dns.txt), [[配置详情]](https://github.com/YishaBei/adblock-filter/blob/2c367c734743b82276dbfd94912a2269f5569af2/src/main/resources/application.yml)，出现了过多的重复规则，我尝试随意搜索了两个广告拦截规则热门拦截的网址，其中 `track.uc.cn` 因为^这个在该文件中没用的分隔符[[参考]](https://adguard.com/kb/general/ad-filtering/create-own-filters/#:~:text=a%20separator%20character%20mark)而出现了两次， `data.bilibili.com` 更是因为未知原因出现了四次，这导致了文件过于冗杂，还望开发者能尽快修复，谢谢！

**Comment by YishaBei** [comment]
问题似乎没有得到完全解决 [[dns.txt]](https://raw.githubusercontent.com/YishaBei/adblock-filter/7bdceac1fd68b1421bb46253c9faa18bab0115f2/rule/dns.txt) [[easylist.txt]](https://raw.githubusercontent.com/YishaBei/adblock-filter/7bdceac1fd68b1421bb46253c9faa18bab0115f2/rule/easylist.txt) [[配置参考]](https://github.com/YishaBei/adblock-filter/blob/7bdceac1fd68b1421bb46253c9faa18bab0115f2/src/main/resources/application.yml)

通过对比上述文件不难看出，已经解决了很多问题，但其中因为我的表达失误：
```
||httpdns*.dbankcloud.$important
||hiboard-*.dbankcdn.$important
```
这两个可以被 `AdGuard Home` 正确识别(详情见上图)，但仍然会被分配到 `easylist.txt`

此外虽然重复规则探测得到极大改善，但同时也引入了一些 `AdGuard Home` 无法正常识别的规则，例如：
```
serve.uberads.com^$domain=serve.uberads.com
req.tidaltv.com^$domain=req.tidaltv.com
sjc-bid.contextweb.com^$domain=sjc-bid.contextweb.com
astrategy.beacon.qq.com^$domain=astrategy.beacon.qq.com
s.ixiaa.com^$domain=s.ixiaa.com
```
目前观察到的仅有 `^$domain=` 混入进去成为了无效规则，也不排除有其它，但可以查阅下文的文档决定建立白名单的范围。

正则表达式与**其它特殊语法**的缺失：
`AdGuard Home` 兼容基本的正则表达式和特殊语法，还望能将其正确分配到其中，例如：
```
/example.*/
@@/example.*/$important
||example.org^$client=127.0.0.1,dnstype=A
$dnstype=~value1|value2
||example.com^$dnsrewrite=NOERROR;CNAME;example.net
```

建议参考链接：
[AdGuard DNS 过滤规则语法](https://adguard-dns.io/kb/zh-CN/general/dns-filtering-syntax/)

**Comment by fordes123** [comment]
`^$domain=` 是由我对规则理解有误导致的，将尽快修复  

---
此外似乎有些误解  
我们并不以 AdGuard 规则为标准，AdBlock 规则是复杂的，具有多种组合，解析和测试都不易
目前只专注于处理基本规则，也即只包含 `域名` 或是 `带通配符的域名`  的规则，除 `$important` 外任何控制符都不会识别

**Comment by YishaBei** [comment]
好的，问题似乎得到解决了 感谢。
