### ISSUE TITLE
反应一个很奇怪的问题

### ISSUE THREAD

**Issue by xiulou23** [fordes123/ad-filters-subscriber#32]
我添加了一个加速网站的host规则，然后查重。发现host规则中的ipv4变成ipv6，然后有些网站不支持ipv6然后就访问不了。
![image](https://github.com/user-attachments/assets/54c6efa4-62f5-428a-b4cd-b9dfb57b6cbd)
这是原本的host规则
![image](https://github.com/user-attachments/assets/90d94f8f-899a-4180-8155-4d8f66daaf09)
这是我的host规则链接：https://github.com/xiulou23/FastHostSync/blob/main/Hosts
全部都是ipv4，但是查重后都变成ipv6了

**Comment by xiulou23** [comment]
https://mirror.ghproxy.com/https://raw.githubusercontent.com/xiulou23/AdguardHome-demonicAsura/v2/rule/easylist.txt
这是我的广告过滤规则链接，里面加上了我的加速网址的host规则，你试一下把它放在adguard home。然后进入GitHub，然后你就会发现ip地址变成ipv6了，在host规则链接中所有域名对应的IP都是ipv4
![image](https://github.com/user-attachments/assets/53b94d1f-afed-461a-851a-7c3215d41fc1)

**Comment by fordes123** [comment]
该内容来自配置文件中以下部分，与本程序无关
```
- name: "guandasheng"
  path: 'https://github.guanmengkai.bf/https://raw.githubusercontent.com/guandasheng/adguardhome/main/rule/all.txt'
```

**Comment by xiulou23** [comment]
> 该内容来自配置文件中以下部分，与本程序无关
> ```
> - name: "guandasheng"
>   path: 'https://github.guanmengkai.bf/https://raw.githubusercontent.com/guandasheng/adguardhome/main/rule/all.txt'
> ```

明白了，多谢
