### ISSUE TITLE
我想fork你的项目，但是总是失败

### ISSUE THREAD

**Issue by Shura23** [fordes123/ad-filters-subscriber#33]
还有我记得你的项目是有rule文件夹的，但是怎么不见了？我之前fork过你的项目，现在删除原来的项目，打算重新fork
![image](https://github.com/user-attachments/assets/8081527c-54fc-4579-8d47-240ebf14b2f4)

![image](https://github.com/user-attachments/assets/dbf0ea4f-b5b1-4150-ae8c-a8813d3e22b8)

**Comment by fordes123** [comment]
1. 不清楚，建议控制变量多试几次  
2. 输出目录在配置文件中定义就行，如不存在会自动创建

**Comment by Shura23** [comment]
> 1. 不清楚，建议控制变量多试几次
> 
>     2. 输出目录在配置文件中定义就行，如不存在会自动创建

已经成功了，我把一些广告过滤扩展关闭后就正常了，应该是被拦截了
