### ISSUE TITLE
想到一个问题

### ISSUE THREAD

**Issue by 2584191127** [fordes123/ad-filters-subscriber#6]
去重合并确实挺好的，但是如果出现误杀的话那就不好排查问题了。能不能只去重不合并呢？

**Comment by fordes123** [comment]
好的想法，但是我们的定位是对规则进行整合分发，而非维护.
对于误杀排查，由于部分规则不支持尾注，我们以注释的形式标注每段规则的来源.
实际使用中，可以将错误规则加入白名单，或者搜索定位到规则所在行，再向上寻找注释以确认规则来源.

**Comment by 2584191127** [comment]
> 好的想法，但是我们的定位是对规则进行整合分发，而非维护. 对于误杀排查，由于部分规则不支持尾注，我们以注释的形式标注每段规则的来源. 实际使用中，可以将错误规则加入白名单，或者搜索定位到规则所在行，再向上寻找注释以确认规则来源.

说的也是，毕竟误杀还是很少发生的。
另外我想提一个建议，就是在文件开头加上标题（仓库名）、时间（规则构建时间）和主页（仓库链接），如下图
![image](https://user-images.githubusercontent.com/78305714/229287955-0ef0f4ed-cce7-43c9-8da7-891e4bee3f0c.png)

**Comment by fordes123** [comment]
收到~
