### ISSUE TITLE
能否适配圈x等一些vpn软件的规则编写方法

### ISSUE THREAD

**Issue by afwfv** [fordes123/ad-filters-subscriber#9]
如题

**Comment by fordes123** [comment]
在不同格式间转换并不容易。同时我认为这也不是这个程序所需要的功能

**Comment by afwfv** [comment]
另外adhome新版本更新了单行规则不能超过1024个字节，我们规则合并好像会出现这个问题，假如想在adhome使用all规则就添加不了
https://github.com/AdguardTeam/AdGuardHome/issues/6003
